### ISSUE TITLE
install dmd fails on macOS-latest due to GPG

### ISSUE THREAD

**Issue by SingingBush** [mihails-strasuns/setup-dlang#16]
thanks for the effort on setup-dlang, github workflows have so far been much faster than my travis-ci builds.

I have a build failure https://github.com/SingingBush/dfract/runs/316832424 on macOS due to the attempt to verify the dmd download from dlang.org:

```
Run mihails-strasuns/setup-dlang@v0.4.0
  with:
    compiler: dmd-latest
Enabling dmd-latest
Downloading http://downloads.dlang.org/releases/2.x/2.089.0/dmd.2.089.0.osx.tar.xz
Verifying the download with GPG
Error: spawn gpg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn gpg',
  path: 'gpg',
  spawnargs: [
    '--lock-never',
    '--verify',
    '--keyring',
    '/Users/runner/runners/2.160.2/work/_temp/f35205f3-235a-41be-8100-522979334adc',
    '--no-default-keyring',
    '/Users/runner/runners/2.160.2/work/_temp/da51173a-421b-4475-b111-4ef08656158f',
    '/Users/runner/runners/2.160.2/work/_temp/ae1334d8-d80b-44d2-886a-6fa5ce69556e'
  ]
}
##[error]spawn gpg ENOENT
##[error]Node run failed with exit code 1
```

Also, dlang.org has an SSL cert so it may be better to use https://downloads.dlang.org/ for the download

**Comment by WebFreak001** [comment]
in the commit which added GPG verification it added

```yaml
      - run: brew install gnupg
        if: matrix.os == 'macOS-latest'
```

to the test. Maybe we should add this code to the readme or install it from within setup-dlang (I would think that is nicer)

downloads.dlang.org doesn't have HTTPS, which is why we are doing this GPG verification. [On the forums](https://forum.dlang.org/thread/slzfdbkgvernfneqnkvq@forum.dlang.org) it resulted that HTTPS would cost a lot extra because it's using AWS to serve the files.

**Comment by SingingBush** [comment]
doing it as part of setup-dlang would be ideal.
